#pragma once

// Window and display
#define GAME_WINDOW_ICON_PATH "icon.png"
#define GAME_WINDOW_TITLE "Nonograms Testing"

#define GAME_DEFAULT_SCREEN_WIDTH  1680U
#define GAME_DEFAULT_SCREEN_HEIGHT 1050U
#define GAME_MINIMUM_SCREEN_WIDTH  1280U
#define GAME_MINIMUM_SCREEN_HEIGHT 720U

